// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1:string):Promise<string>;

export function DeleteTemplate(arg1:string):Promise<string>;

export function FindMatches(arg1:string):Promise<string>;

export function GetTemplateDetail(arg1:string):Promise<string>;

export function GetTemplatesList():Promise<string>;

export function SaveTemplate(arg1:string):Promise<string>;
