// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1) {
  return window['go']['main']['App']['ApplyChanges'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function FindMatches(arg1) {
  return window['go']['main']['App']['FindMatches'](arg1);
}

export function GetTemplateDetail(arg1) {
  return window['go']['main']['App']['GetTemplateDetail'](arg1);
}

export function GetTemplatesList() {
  return window['go']['main']['App']['GetTemplatesList']();
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}
